networks:
    project-network:
        driver: bridge

services:
    postgres-kivo:
        image: postgres:13.3-alpine
        environment:
            DATABASE_HOST: 127.0.0.1
            POSTGRES_DB: postgres
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
        volumes:
            - ./database/backup:/tmp/backup
            - ./database/postgres:/var/lib/postgresql/data
        networks:
            - project-network
        ports:
            - 5432:5432
        deploy:
            resources:
                limits:
                    cpus: '2.5'
                    memory: '1000M'

    pgadmin-kivo:
        image: dpage/pgadmin4
        networks:
            - project-network
        environment:
            PGADMIN_DEFAULT_EMAIL: darinel@hotmail.com
            PGADMIN_DEFAULT_PASSWORD: root
            PGADMIN_LISTEN_PORT: "81"
        ports:
        - "81:81"
        deploy:
            resources:
                limits:
                    cpus: '1.5'
                    memory: '1000M'
        depends_on:
            - postgres-kivo

    frontend-app-kivo:
        image: frontend-app
        build:
            context: ./
            dockerfile: ./docker/nodeJs.DockerFile
        networks:
            - project-network
        ports:
            - 8181:8181
        volumes:
            - ./frontend/kivo-project:/app 
            - ./docs:/usr/share/docs
        deploy:
            resources:
                limits:
                    cpus: '5'
                    memory: '6500M'
    nginx-app:
        image: nginx:alpine 
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        depends_on:
            - frontend-app-kivo